-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Operator CASCADE;
DROP TABLE IF EXISTS Poll CASCADE;
DROP TABLE IF EXISTS PollAndOperator CASCADE;
DROP TABLE IF EXISTS Option CASCADE;
DROP TABLE IF EXISTS Vote CASCADE;